name: Galactic Binary Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '03 4 * * *'

jobs:
  galactic_binary:
    uses: ./.github/workflows/industrial_ci.yml
    strategy:
      fail-fast: false
      matrix:
        ROS_DISTRO: [galactic]
        ROS_REPO: [main, testing]
    with:
      ROS_DISTRO: ${{ matrix.ROS_DISTRO }}
      ROS_REPO: ${{ matrix.ROS_REPO }}
      UPSTREAM_WORKSPACE: Universal_Robots_ROS2_Driver-not-released.${{ matrix.ROS_DISTRO }}.repos
